### ISSUE TITLE
Change Page automatically when user searches

### ISSUE THREAD

**Issue by rishikesh2003** [rishikesh2003/worldbook-reactjs#3]
I've added pagination to the app, but when a user searches by going to the page 8, the results appear on page 1 though but it will not automatically switch to page 1

**Comment by jbasso-dev** [comment]
I would like to try to fix it, could you assign it to me @rishikesh2003 ?

**Comment by rkeshs** [comment]
Thanks for your effort, i already fixed that. 😃

**Comment by rkeshs** [comment]
I would be happy if you can review the code and can do some improvements or adding a new feature! 😃
